### PR TITLE
Remove outdated images when making new changes (fix #16)

### LINKED ISSUE #16: Docker creating whole new images
Whenever there's a new change, running `make` or `make all` will cause Docker to create a whole new image, like so:
```
REPOSITORY             TAG                 IMAGE ID            CREATED              SIZE
pollex                 dev                 00784ad056ea        3 seconds ago        927MB
<none>                 <none>              9d964100ad75        About a minute ago   927MB
<none>                 <none>              26cd6bd148a1        2 minutes ago        927MB
```

### PR DESCRIPTION
**Pull request by gabrielrspupo**
A Docker image can't be modified, so every time there's an update in the project, a new image will be created, and the outdated one will lose reference to its original container. `docker image prune` will exclude all dangling images that once belonged to the `pollex` repository.

### CODE REVIEW

**Comment by ET33** [comment]
I don't think we should remove `instance/`. Though it's not supposed to be changed a lot, it would be interesting to have it copied over to the container since it contains relevant files in it. Actually, maybe we should discuss this matter in #15 instead.

Other than that, this looks fine!

**Comment by gabrielrspupo** [comment]
The only reason I removed `instance/` from the Dockerfile and Makefile was to be able to compile the project (folder doesn't exist on filesystem), please put it back if that's necessary.

**Comment by ET33** [comment]
As explained in [here](https://exploreflask.com/en/latest/configuration.html#instance-folder)
> ... The instance folder is a sub-directory of the repository root and contains a configuration file specifically for this instance of the application. We don’t want to commit it into version control.

We shouldn't put this directory in the repository. So, we could configure Dockerfile to generate this directory + config file or something like that.

**Comment by gabrielrspupo** [comment]
`instance` is back on compile instructions. Please review this pull request.

**Comment by ET33** [comment]
Thanks! seems to be working great

**Pull request merged**
