### PR TITLE
Angular project

### PR DESCRIPTION
**Pull request by LuisF3**
Angular project initiated.
Basic routes and pages for login and sign-up implemented. Now it is interesting to wait for the backend team to finish the authentication process. After that, we may implement it in angular and, just then, implement the working application.

### CODE REVIEW

**Comment by ET33** [comment]
Hi, I'm currently setting the our Flask application and one feature that comes with it is the Jinja2 template engine. They have different purposes, but they share some syntax that could trouble us later. [See this](https://stackoverflow.com/questions/30362950/is-it-possible-to-use-angularjs-with-the-jinja2-template-engine).
So I suggest we choose one of the 4 workarounds listed:
> 1. Change the delimiter notation for Angular
> 2. Change the delimiter notation for Jinja2
> 3. Output a raw block in Jinja2 using {% raw %} or {% verbatim %}
> 4. Use Jinja2 to write the curly braces in the template

Personally, 1. and 2. seems more attractive to me.

I'm also organizing the directories following the Flask conventions, so *I* think that it would be better if we wait a bit before merging this PR.

**Comment by LuisF3** [comment]
So... 
First, the project is not in AngularJS as it was discontinued.

Second, I think it is better to use a REST approach with Jsons so that the backend and frontend can remain independent. 

With this approach, the backend team would only provide specific routes for data retrieving or processing.

Example: The user wants to authenticate.
He is going to type username and password on angular, hit login and, then, angular will the following json to the route `/auth`. 
`{ "username": "LuisF3", "password": "teste123" }`

Flask will receive and process it, returning a json with some information, like a token and the user id.
`{ "id": 321, "token": "$$$$$$$$$" }`

[How to retrieve the json angular is going to send:
](https://stackoverflow.com/questions/40072136/can-i-use-angular-js-as-templating-engine)

> request property json
> The parsed JSON data if mimetype indicates JSON (application/json, see is_json()).
> 
> Calls get_json() with default arguments.

**Conclusion:**
[Angular is not a template engine](https://stackoverflow.com/questions/40072136/can-i-use-angular-js-as-templating-engine) (post about angularJs, but they have the same philosophy) and it shall not be used like that. 
The point is that, if we are going to use angular, a template engine wont be necessary. It is a Client-side only application that will communicate to flask throught jsons.

**Comment by LipArcanjo** [comment]
In the classe was decided we would have two servers, one for the front-end and other for the back-end, in that approach, the back- end server( the flask server) won't Deal with templates, It just gonna communicate with the front-end through json requests

**Comment by ET33** [comment]
At first I thought we were going for a hybrid approach since the original html files weren't moved/deleted.

Since that's the case, I'll rearrange things on my side.

**Comment by LuisF3** [comment]
That's nice to hear. I think it is going to be easier to maintain both frontend and backend independent this way.

@ET33, do you need any help rearranging things? 

I think it would be interesting if you could implement a route `/auth` that allows only post requests and receives 2 parameters, **username** and **password**, and returns a **token**.
For now, it would be enough to return anything as token, just for testing (we dont have a database to get/save the token anyway). @LipArcanjo may be able to help you.

**Comment by ET33** [comment]
For now I'm good, thanks! I didn't go that far anyway, still looking at the docs most of the time.

**Comment by ET33** [comment]
@LuisF3 Would #10 be enough for your testing? I'll keep digging into other solutions for improvement but maybe that's enough to keep you going while I'm at it.

**Comment by Vakihito** [comment]
@LuisF3 , just remember to specify how to create the enviroment

**Comment by ET33** [comment]
> @LuisF3 , just remember to specify how to create the enviroment

It is somewhat specified in pollex-angular/README.md, though you still need to install [angular-cli](https://github.com/angular/angular-cli) by yourself, and npm packages.

**Comment by LuisF3** [comment]
As I said in class, the Git tutorial and conventions had not been released by the time I created this pull request. That said, it would be simpler if we just let this one pass. I promise I will commit to develop next time.

**Pull request merged**
